steps:

  - name: ":docker::package:"
    plugins:
      docker-compose#5cd8b85:
        build: app
        # Dockerfile expects the binary to be built
        pre-command: make

  - wait

  - name: ":golang:"
    command: "go test"
    parallelism: 10
    plugins:
      docker-compose#5cd8b85:
        run: app
        # Dockerfile expects the binary to be built
        pre-command: make
