steps:

  - name: ":docker::package:"
    agents:
      queue: ${BUILDKITE_AGENT_META_DATA_QUEUE}
    plugins:
      docker-compose:
        build: app

  - wait

  - name: ":golang:"
    command: "go test"
    parallelism: ${TEST_PARALLELISM:-10}
    agents:
      queue: ${BUILDKITE_AGENT_META_DATA_QUEUE}
    plugins:
      docker-compose:
        run: app

  - wait

  - trigger: "${BUILDKITE_PIPELINE_SLUG}-deploy"
    label: ":shipit:"
    branches: "master"
    async: true
    build:
      message: ${BUILDKITE_MESSAGE}
      commit: ${BUILDKITE_COMMIT}
      branch: ${BUILDKITE_BRANCH}
