steps:

  - name: ":docker::package:"
    plugins:
      docker-compose#2db7f2b:
        build: app
        build-script: "make docker"

  - wait

  - name: ":golang:"
    command: "go test"
    parallelism: 10
    plugins:
      docker-compose:
        run: app
