steps:

  - name: ":docker::package:"
    agents:
      queue: elastic
    plugins:
      docker-compose:
        build: app

  - wait

  - name: ":golang:"
    command: "go test"
    parallelism: 10
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: app
