steps:

  - name: ":docker::package:"
    agents:
      queue: $BUILDKITE_AGENT_META_DATA_QUEUE
    plugins:
      docker-compose:
        build: app

  - wait

  - name: ":golang:"
    command: "go test"
    parallelism: 10
    agents:
      queue: $BUILDKITE_AGENT_META_DATA_QUEUE
    plugins:
      docker-compose:
        run: app

  - wait

  - trigger: "backend-deploy"
    label: ":shipit:"
    branches: "master"
    async: true
    build:
      message: ${BUILDKITE_MESSAGE}
      commit: ${BUILDKITE_COMMIT}
      branch: ${BUILDKITE_BRANCH}
